### PR TITLE
fixed tests to run on php-5.2

### PR DESCRIPTION
**Pull request by tonich-sh**

### CODE REVIEW

**Comment by StefanYohansson** [comment]
@maldoinc @lichtner @cbornhoft I think this PR is bug safe and a good improvement, if we really want to define base version as 5.1+

**Comment by maldoinc** [comment]
It doesn't break anything, however I think we should set PHP 5.3 as the minimum supported version since it's the most popular and it's already old enough(5.3.4 was released in Dec 2010).

FYI 5.1 was released in Nov 2005 and I see no reason to have that as the min. version.

So while the PR is fine in itself, if we're gonna stick to 5.3+ this PR is no good.

**Comment by StefanYohansson** [comment]
I think 5.3+ is good enough too. When we clear opened PRs, we can release a new version and drop  5.1+ support (hypothetically) and change it to 5.3+.

**Comment by lichtner** [comment]
I agree with 5.3+

**Comment by lichtner** [comment]
can somebody check fpdo with php 7? I hope it works. Than we can add php 7 in `.travis.yml` for testing.

**Comment by maldoinc** [comment]
I say we just add one and let travis do it's thing. I'll set up a php7 branch.

**Comment by maldoinc** [comment]
We'll close this since we're all on board for PHP5.3+

**Comment by nblackman** [comment]
Is it too late to add a vote for PHP 5.2? I'm stuck with 5.2 on a project that was using FluentPDO. The only compatibility issue I see is the recently merged closures in #137.

**Comment by StefanYohansson** [comment]
We can vote to define a 1.0.0 release using 5.2 support and release a 2.0.0 version to drop it. What you think guys? @lichtner @maldoinc @cbornhoft

**Comment by lichtner** [comment]
@StefanYohansson No problem. But I think fpdo should move forward. Always will be users who are stack on some old envi. At least 2.0.0 should drop 5.2 support.

**Comment by StefanYohansson** [comment]
@lichtner Yes, we need to move forward. We can define 1.x final version for legacy systems who needs this. So we can move forward in next releases.

**Pull request closed without merging**
