### PR TITLE
fix onDuplicateKeyUpdate bug on set "0" value and  run-tests.php compare results issue with whitespaces

### PR DESCRIPTION
**Pull request by PHPCraftdream**

### CODE REVIEW

**Comment by PHPCraftdream** [comment]
Travis CI check fails because first commit jusf fix test "33-insert-update" to manifest the bug and issue. It fixed by next commits.

**Comment by maldoinc** [comment]
Please follow the same code formatting conventions as used in the rest of the library.

**Comment by PHPCraftdream** [comment]
Anything else?

**Comment by maldoinc** [comment]
The tests need to successfully run as well.

**Comment by PHPCraftdream** [comment]
Latest commit will pass tests ...

What should I do? Don't know, sorry.

**Pull request closed without merging**
